# Generated by Django 6.0.4 on 2026-05-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_add_orderitem_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendente"),
                    ("PROCESSING", "Processando"),
                    ("PAID", "Pago"),
                    ("SHIPPED", "Enviado"),
                    ("DELIVERED", "Entregue"),
                    ("CANCELLED", "Cancelado"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
