# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_add_payment_id_and_update_status_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_neighborhood",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_postal_code",
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_state",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_street",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="lgpd_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="lgpd_consented_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_provider_status",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
