# Generated by Codex on 2026-06-01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_checkout_delivery_consent_provider_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="payment_method_id",
            new_name="payment_id",
        ),
    ]
