# Generated by Codex on 2026-06-05

from django.db import migrations, models


def backfill_processing_started_at(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    Order.objects.filter(
        status="PROCESSING",
        processing_started_at__isnull=True,
    ).update(processing_started_at=models.F("updated_at"))


def clear_processing_started_at(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    Order.objects.update(processing_started_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_rename_payment_method_id_to_payment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="processing_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            backfill_processing_started_at,
            clear_processing_started_at,
        ),
    ]
