# Generated by Django 6.0.4 on 2026-06-05 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_active_product_price_gt_0'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
